version: "3.9"
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: harvesthub@257
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-db-volume:
